# fly.toml app configuration file generated for casa-da-crian-a-batuira on 2026-06-17T20:08:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casa-da-crian-a-batuira'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[[mounts]]
  source = 'batuira_data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
